INIT:
	ORG 0x00
	BCF STATUS,RP1	
	BSF STATUS,RP0
	CLRF TRISB	; TRISB=0 para portC ser OUTPUT
	BCF STATUS,RP0
	MOVLW 1
	MOVWF PORTB	;Iniciando PORTC COM PRIMEIRO BIT
LOOP:
	RLF PORTB,1 ;DESLOCA BITS PARA DIREITA
	BTFSC PORTB,7 ; Verifica se o bit 7 está ativo, se sim executa a proxima linha
	MOVWF PORTB
	GOTO LOOP