INIT:
	ORG 0X00
	BCF STATUS,RP1
	BSF STATUS,RP0
	CLRF TRISB ; TRISB = 0 para PORTB ser OUTPUT
	BCF STATUS,RP0 ; 
	MOVLW 85 ; SETANDO A PORTA B COM 01010101 85 Decimal
	MOVWF PORTB
LOOP:
	COMF PORTB,1 ; SETANDO A PORTA B COM O SEU COMPLEMENTAR
	GOTO LOOP
