INIT:
	ORG 0x00
	BCF STATUS,RP1	
	BSF STATUS,RP0
	CLRF TRISC	; TRISC=0 para portC ser OUTPUT
	BCF STATUS,RP0
	MOVLW 1
	MOVWF PORTC	;Iniciando PORTC COM PRIMEIRO BIT
LOOP:
	RLF PORTC,1 ;DESLOCA BITS PARA DIREITA
	GOTO LOOP